const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
let session=null,source=null,snap=null,screen='',joining=false,connected=false,mapOpen=false,w=innerWidth,h=innerHeight,scale=1,camera={x:1200,y:1200},pointer={x:innerWidth/2,y:innerHeight/2,fire:false},lastHud=0;
let motion=new RenderBuffer();
const held=new Set(),fmt=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`,me=()=>snap?.players.find(p=>p.slot===session?.slot);
function showError(e){$('error')?$('error').textContent=e.message:$('net').textContent=e.message;}
function lobby(){screen='lobby';$('content').innerHTML=`<div class="eyebrow">DROP IN. GEAR UP. BE THE LAST.</div><h1>마지막 신호는<br><em>단 하나.</em></h1><p>착지 지점부터 생존은 당신의 선택.<br>무기와 탄약을 확보하고, 좁혀오는 자기장 안에서 친구와 맞서세요.</p><div class="divider"></div><div class="row"><button class="primary" id="create">전장 만들기 ↗</button><span class="small">또는</span><input id="code" maxlength="6" placeholder="방 코드" aria-label="방 코드"><button id="join">코드로 참가</button></div><div id="error" class="error"></div><div class="features"><div><b>01 / DROP</b><span>지도에서 직접 착지 선택</span></div><div><b>02 / LOOT</b><span>총기 · 탄약 · 회복제 파밍</span></div><div><b>03 / SURVIVE</b><span>은폐와 수동 사격, 마지막 1인</span></div></div>`;$('create').onclick=()=>enter(true);$('join').onclick=()=>enter(false);$('code').onkeydown=e=>{if(e.key==='Enter')enter(false);};}
async function enter(host){if(joining)return;joining=true;const code=$('code')?.value.trim().toUpperCase();try{if(source)await source.close();session=null;snap=null;motion=new RenderBuffer(host?40:90);source=new OnlineGame(s=>{snap=s;motion.push(s,performance.now());if(session)ui();},ok=>{connected=ok;$('net').textContent=ok&&session?`ROOM ${session.room} · ${session.slot+1}P`:'연결 중…';});session=await source.open(host,code);$('net').textContent=`ROOM ${session.room} · ${session.slot+1}P`;screen='';if(snap)ui();}catch(e){await source?.close();source=null;session=null;connected=false;showError(e);}finally{joining=false;}}
function action(path,data={}){if(session&&connected)source.action(path,{...data,match:snap?.match});}
function ui(){const s=snap,p=me();if(!p)return;const active=['playing','dropping','paused','disconnected','finished'].includes(s.state);$('hud').hidden=!active;$('loadout').hidden=!active;$('mini').hidden=!active;$('pause').hidden=!['selecting','dropping','playing','paused','disconnected'].includes(s.state);
  const now=performance.now();if(now-lastHud>90){lastHud=now;$('health').innerHTML=`<b>${p.slot+1}P · YOU</b> <span class="small">${Math.ceil(p.hp)} HP</span><div class="health"><i style="width:${p.hp}%"></i></div>`;$('zone').innerHTML=`<b>${s.alive} ALIVE</b> <span class="small"> / ${fmt(s.time)}</span><br><span class="small">자기장 ${s.zone.phase}단계 · ${s.zone.shrinking?'축소 중':'축소까지'} ${Math.ceil(s.zone.remaining)}초</span>`;const gun=p.gun?Battle.weapons[p.gun]:null;$('loadout').innerHTML=`<div class="eyebrow">${gun?gun.name:'UNARMED'}</div><div class="ammo">${p.mag||0} <span class="small">/ ${gun?p.ammo[gun.ammo]:0}</span></div><div class="small">9mm ${p.ammo.light} · 5.56mm ${p.ammo.heavy} · 회복제 ${p.meds}</div><div class="small">${p.reloading>0?'장전 중 '+p.reloading.toFixed(1)+'초':p.healing>0?'치료 중 '+p.healing.toFixed(1)+'초':gun?'R 장전 · Q 치료':'F로 무기를 주우세요'}</div>`;}
  $('dropBanner').hidden=s.state!=='dropping';if(s.state==='dropping')$('dropBanner').innerHTML=`<div class="eyebrow">DEPLOYING</div><b>선택한 위치로 강하 중 · ${Math.max(0,3-s.dropTime).toFixed(1)}초</b>`;
  const next=s.state+'-'+s.match+(s.state==='waiting'?s.players.map(p=>p.online).join():'' );
  if(next!==screen){screen=next;pointer.fire=false;mapOpen=false;$('panel').hidden=['playing','dropping','selecting'].includes(s.state);const box=$('content');
    if(s.state==='waiting'){box.innerHTML=`<div class="eyebrow">2 PLAYER PVP / LOBBY</div><h2>친구와 같은 전장으로.</h2><p>같은 사이트에서 아래 코드를 입력하세요. 두 명이 모이면 시작합니다.</p><h1 style="color:var(--accent);letter-spacing:8px">${s.code}</h1><p>${s.players.length} / 2 참가 · ${s.players.every(p=>p.online)?'연결됨':'연결 대기 중'}</p><button class="primary" id="start" ${session.slot!==0||s.players.length<2||s.players.some(p=>!p.online)?'disabled':''}>착지 지점 선택하기 →</button><div id="error" class="error"></div>`;$('start').onclick=()=>action('/start');}
    if(['paused','disconnected'].includes(s.state)){box.innerHTML=`<div class="eyebrow">MATCH ON HOLD</div><h2>${s.state==='paused'?'전장이 잠시 멈췄습니다.':'연결 복구를 기다립니다.'}</h2><p>두 사람 모두 연결된 후 계속할 수 있습니다.<br>방장 탭은 열어두세요. 새로고침했다면 새 방이 필요합니다.</p><button class="primary" id="resume">계속하기 →</button>`;$('resume').onclick=()=>action('/pause');}
    if(s.state==='finished'){box.innerHTML=`<div class="eyebrow">MATCH COMPLETE</div><h1>${s.winner===null?'동시 탈락.':s.winner===session.slot?'LAST<br><em>SURVIVOR.</em>':'다음 전장을<br>기약하며.'}</h1><p>${s.winner===null?'승자 없음':`${s.winner+1}P 최후의 생존자`} · ${fmt(s.time)}<br>가한 피해 ${Math.round(p.damage)} · ${p.kills} KILLS</p><button class="primary" id="restart" ${session.slot!==0?'disabled':''}>새 매치 →</button><p>${session.slot===0?'새 매치에서는 착지 지점부터 다시 선택합니다.':'방장이 새 매치를 시작할 수 있습니다.'}</p>`;$('restart').onclick=()=>action('/start');}
  }
  $('mapPanel').hidden=!(s.state==='selecting'||mapOpen);$('mapClose').hidden=s.state==='selecting';
  if(s.state==='selecting'){$('mapTitle').textContent=p.selected?'착지 지점 확정 · 상대를 기다리는 중':'착지할 위치를 선택하세요';$('mapNote').textContent=`${Math.max(0,Math.ceil(20-s.selectTime))}초 후 자동 배치 · ${p.selected?'위치 선택 완료':'건물 지붕을 선택하면 내부로 착지합니다.'}`;}
}
function resize(){w=innerWidth;h=innerHeight;scale=Math.max(.55,Math.min(w/1280,h/800));const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize);resize();
function circle(c,x,y,r,color){c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=color;c.fill();}
function drawMap(c,width,s){const factor=width/Battle.SIZE;c.clearRect(0,0,width,width);c.fillStyle='#28392b';c.fillRect(0,0,width,width);c.save();c.scale(factor,factor);c.strokeStyle='#70815733';c.lineWidth=2/factor;for(let n=0;n<=2400;n+=400){c.beginPath();c.moveTo(n,0);c.lineTo(n,2400);c.moveTo(0,n);c.lineTo(2400,n);c.stroke();}for(const h of Battle.buildings){c.fillStyle='#b5b593';c.fillRect(h.x,h.y,h.w,h.h);}for(const b of Battle.bushes)circle(c,b.x,b.y,b.r,'#4f7744');if(s){c.beginPath();c.rect(0,0,2400,2400);c.arc(1200,1200,s.zone.r,0,Math.PI*2,true);c.fillStyle='#6687ff55';c.fill('evenodd');c.strokeStyle='#d8e9ff';c.lineWidth=2/factor;c.beginPath();c.arc(1200,1200,s.zone.next,0,Math.PI*2);c.stroke();const p=me();if(p&&Number.isFinite(p.x)&&(s.state!=='selecting'||p.selected)){circle(c,p.x,p.y,5/factor,'#f1f3a0');c.strokeStyle='#162417';c.lineWidth=2/factor;c.stroke();}}c.restore();c.fillStyle='#b7c4a1';c.font='11px monospace';c.fillText('N ↑',8,16);}
function drawLoot(o){const colors={weapon:'#ffe09a',ammo:'#b9dcec',med:'#9ef3bc'},color=colors[o.type];circle(ctx,o.x,o.y,13,color+'20');ctx.strokeStyle=color;ctx.lineWidth=2;if(o.type==='weapon'){ctx.fillStyle=color;ctx.fillRect(o.x-11,o.y-3,22,5);ctx.fillRect(o.x+1,o.y,4,8);}else if(o.type==='ammo'){ctx.strokeRect(o.x-6,o.y-7,12,14);ctx.beginPath();ctx.moveTo(o.x,o.y-5);ctx.lineTo(o.x,o.y+5);ctx.stroke();}else{ctx.fillStyle=color;ctx.fillRect(o.x-3,o.y-9,6,18);ctx.fillRect(o.x-9,o.y-3,18,6);}}
function render(){const view=motion.sample(performance.now())||snap,p=view?.players.find(q=>q.slot===session?.slot);if(p&&Number.isFinite(p.x)){camera.x+=(p.x-camera.x)*.25;camera.y+=(p.y-camera.y)*.25;}ctx.fillStyle='#142a29';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(scale,scale);ctx.translate(-camera.x,-camera.y);ctx.fillStyle='#35452c';ctx.fillRect(0,0,2400,2400);
  ctx.fillStyle='#696548';ctx.fillRect(0,1120,2400,110);ctx.fillRect(1115,0,110,2400);ctx.strokeStyle='#94926a';ctx.setLineDash([18,22]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,1175);ctx.lineTo(2400,1175);ctx.moveTo(1170,0);ctx.lineTo(1170,2400);ctx.stroke();ctx.setLineDash([]);
  for(let i=0;i<350;i++){const x=25+i*131%2350,y=25+i*307%2350;ctx.fillStyle=i%2?'#52603c':'#3f5130';ctx.fillRect(x,y,3,8);}
  for(const b of Battle.bushes)circle(ctx,b.x,b.y,b.r,'#2d5027');
  for(const h of Battle.buildings){ctx.fillStyle='#171e16';ctx.fillRect(h.x+6,h.y+8,h.w,h.h);ctx.fillStyle='#92846a';ctx.fillRect(h.x,h.y,h.w,h.h);ctx.strokeStyle='#6c604f';ctx.lineWidth=1;for(let y=h.y+20;y<h.y+h.h;y+=22){ctx.beginPath();ctx.moveTo(h.x,y);ctx.lineTo(h.x+h.w,y);ctx.stroke();}ctx.fillStyle='#4c4439';ctx.fillRect(h.x+120,h.y+28,35,22);}
  if(view){for(const o of view.loot)drawLoot(o);for(const b of view.bullets){ctx.strokeStyle='#ffe8a4';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x-b.vx*.014,b.y-b.vy*.014);ctx.lineTo(b.x,b.y);ctx.stroke();}
    for(const q of view.players){if(!q.visible||!q.alive)continue;const mine=q.slot===session.slot,color=mine?'#e5ee94':'#ee9a79';const altitude=view.state==='dropping'?(3-view.dropTime)*55:0;circle(ctx,q.x,q.y+7,17,'#0004');ctx.save();ctx.translate(q.x,q.y-altitude);ctx.rotate(mine?Math.atan2(pointer.y-h/2,pointer.x-w/2):q.angle);ctx.fillStyle='#212b22';ctx.fillRect(-12,-12,19,24);circle(ctx,0,0,12,color);ctx.fillStyle='#293828';ctx.fillRect(3,-8,8,16);if(q.gun){ctx.fillStyle='#171b18';ctx.fillRect(6,4,24,5);}ctx.restore();if(altitude>0){ctx.strokeStyle='#dedebe';ctx.beginPath();ctx.moveTo(q.x-34,q.y-altitude-45);ctx.lineTo(q.x,q.y-altitude);ctx.lineTo(q.x+34,q.y-altitude-45);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(q.x,q.y-altitude-42,38,Math.PI,Math.PI*2);ctx.fill();}}}
  for(const h of Battle.buildings){const reveal=p&&Battle.inside(p,h);if(!reveal){ctx.fillStyle='#62654e';ctx.fillRect(h.x-3,h.y-3,h.w+6,h.h+6);ctx.strokeStyle='#a2a383';ctx.lineWidth=2;ctx.strokeRect(h.x+8,h.y+8,h.w-16,h.h-16);ctx.beginPath();ctx.moveTo(h.x+h.w/2,h.y);ctx.lineTo(h.x+h.w/2,h.y+h.h);ctx.stroke();ctx.fillStyle='#c3bc8c';ctx.font='11px monospace';ctx.fillText('SECTOR '+h.id.slice(1),h.x+20,h.y+32);ctx.fillStyle='#b6aa78';ctx.fillRect(h.x+65,h.y+h.h-7,50,12);}else for(const wall of Battle.walls(h)){ctx.fillStyle='#454c3c';ctx.fillRect(wall.x,wall.y,wall.w,wall.h);}}
  for(const b of Battle.bushes){ctx.globalAlpha=p&&Battle.dist(p,b)<b.r?.25:1;circle(ctx,b.x,b.y,b.r,'#45663b');circle(ctx,b.x-14,b.y-10,28,'#547747');circle(ctx,b.x+16,b.y+9,27,'#3b5e34');ctx.globalAlpha=1;}
  if(view){const z=view.zone;ctx.beginPath();ctx.rect(-5000,-5000,12000,12000);ctx.arc(z.x,z.y,z.r,0,Math.PI*2,true);ctx.fillStyle='#597aee40';ctx.fill('evenodd');ctx.strokeStyle='#9bbaff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(z.x,z.y,z.r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([12,12]);ctx.strokeStyle='#f0f5df88';ctx.lineWidth=2;ctx.beginPath();ctx.arc(z.x,z.y,z.next,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}
  ctx.restore();if(view){drawMap($('mini').getContext('2d'),240,view);if(!$('mapPanel').hidden)drawMap($('tactical').getContext('2d'),600,view);}
  const loot=p&&view?.state==='playing'?view.loot.filter(o=>Battle.dist(p,o)<65).sort((a,b)=>Battle.dist(p,a)-Battle.dist(p,b))[0]:null;
  $('hint').hidden=view?.state!=='playing';if(view?.state==='playing'){$('hint').textContent=loot?'[F] '+(loot.type==='weapon'?Battle.weapons[loot.item].name+' 줍기 / 교체':loot.type==='ammo'?(loot.item==='light'?'9mm':'5.56mm')+' 탄약 '+loot.amount+'발':'회복제 줍기'):Battle.dist(p,view.zone)>view.zone.r?'자기장 밖입니다! 안전 구역으로 이동하세요.':!p.gun?'무기와 탄약을 찾아 F로 주우세요.':p.mag===0?'탄창이 비었습니다 · 탄약을 확보하고 R로 장전하세요.':'좌클릭 사격 · 건물 출입구는 아래쪽입니다.';}
  requestAnimationFrame(render);
}
const bindings={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};
function currentInput(){const k={angle:Math.atan2(pointer.y-h/2,pointer.x-w/2),fire:pointer.fire&&!mapOpen&&snap?.state==='playing'};if(!mapOpen)for(const key of held)if(bindings[key])k[bindings[key]]=true;return k;}
addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(bindings[e.code]){e.preventDefault();held.add(e.code);}if(e.repeat)return;if(e.code==='KeyP')action('/pause');if(e.code==='KeyF')action('/pickup');if(e.code==='KeyR')action('/reload');if(e.code==='KeyQ')action('/heal');if(e.code==='KeyM'&&snap?.state==='playing'){mapOpen=!mapOpen;pointer.fire=false;$('mapTitle').textContent='현재 위치와 안전 구역';$('mapNote').textContent='점선 원은 다음 안전 구역입니다.';ui();}});
addEventListener('keyup',e=>held.delete(e.code));addEventListener('blur',()=>{held.clear();pointer.fire=false;});canvas.addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;});canvas.addEventListener('pointerdown',e=>{if(e.button===0){pointer.fire=true;source?.input(currentInput());}});addEventListener('pointerup',()=>{pointer.fire=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('tactical').onclick=e=>{if(snap?.state!=='selecting'||me()?.selected)return;const rect=e.currentTarget.getBoundingClientRect();const side=Math.min(rect.width,rect.height),left=rect.left+(rect.width-side)/2,top=rect.top+(rect.height-side)/2;const x=(e.clientX-left)/side*2400,y=(e.clientY-top)/side*2400;if(x>=0&&x<=2400&&y>=0&&y<=2400)action('/drop',{x,y});};
$('mapClose').onclick=()=>{mapOpen=false;ui();};$('pause').onclick=()=>action('/pause');setInterval(()=>{if(source&&session&&connected)source.input(currentInput());},50);lobby();render();
