const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const B=require('./battle');
function room(){const r={players:[{slot:0,stream:true},{slot:1,stream:true}]};B.reset(r);r.state='playing';r.players.forEach((p,i)=>{p.x=100+i*180;p.y=100;p.inputAt=Date.now();});return r;}
function step(r,n=30){for(let i=0;i<n;i++)B.update(r,1/30);}
function act(r,slot,path,data={}){B.action(r,r.players[slot],path,{match:r.match,...data});}
test('each player selects a private landing location, drops, then fights',()=>{const r=room();r.state='waiting';B.start(r);assert.equal(r.state,'selecting');act(r,0,'/drop',{x:430,y:600});assert.equal(r.players[0].selected,true);assert.equal(B.snapshot(r,1).players[0].x,undefined);act(r,1,'/drop',{x:1900,y:1800});step(r,1);assert.equal(r.state,'dropping');step(r,91);assert.equal(r.state,'playing');assert.equal(r.players[0].x,430);});
test('selection timeout gives valid automatic landings',()=>{const r=room();B.start(r);step(r,601);assert.equal(r.state,'dropping');assert.ok(r.players.every(p=>p.selected&&!B.blocked(p.x,p.y)));});
test('building walls stop players; bottom doorway is traversable',()=>{const h=B.buildings[0];assert.equal(B.blocked(h.x+3,h.y+50),true);assert.equal(B.blocked(h.x+90,h.y+h.h),false);const r=room(),p=r.players[0];p.x=h.x-15;p.y=h.y+60;p.keys={right:true};step(r,10);assert.ok(p.x<h.x);});
test('roofs and bushes conceal opponent and loot in viewer snapshot',()=>{const r=room(),h=B.buildings[0];r.players[1].x=h.x+50;r.players[1].y=h.y+50;let s=B.snapshot(r,0);assert.equal(s.players[1].visible,false);assert.equal(s.players[1].x,undefined);assert.ok(!s.loot.some(o=>B.inside(o,h)));r.players[0].x=h.x+90;r.players[0].y=h.y+90;s=B.snapshot(r,0);assert.equal(s.players[1].visible,true);assert.ok(s.loot.some(o=>B.inside(o,h)));const bush=B.bushes[0];Object.assign(r.players[1],{x:bush.x,y:bush.y});Object.assign(r.players[0],{x:1200,y:1200});assert.equal(B.snapshot(r,0).players[1].visible,false);Object.assign(r.players[0],{x:bush.x+10,y:bush.y});assert.equal(B.snapshot(r,0).players[1].visible,true);});
test('weapons require independently looted ammunition and manual reload',()=>{const r=room(),p=r.players[0];r.loot=[{id:1,x:p.x,y:p.y,type:'weapon',item:'pistol'},{id:2,x:p.x+5,y:p.y,type:'ammo',item:'light',amount:20}];act(r,0,'/pickup');assert.equal(p.gun,'pistol');assert.equal(p.mag,0);p.keys={fire:true,angle:0};step(r,5);assert.equal(r.bullets.length,0);act(r,0,'/pickup');p.keys={};act(r,0,'/reload');step(r,37);assert.equal(p.mag,12);assert.equal(p.ammo.light,8);});
test('no automatic fire; aimed manual bullets damage only opponent and spend ammo',()=>{const r=room(),p=r.players[0];p.gun='pistol';p.mag=12;step(r,10);assert.equal(p.mag,12);p.keys={fire:true,angle:0};step(r,1);p.keys={};step(r,10);assert.equal(p.mag,11);assert.equal(p.hp,100);assert.equal(r.players[1].hp,76);});
test('walls block bullets even across a fast frame',()=>{const r=room(),h=B.buildings[0],p=r.players[0],q=r.players[1];Object.assign(p,{x:h.x-35,y:h.y+65,gun:'rifle',mag:30,keys:{fire:true,angle:0}});Object.assign(q,{x:h.x+45,y:h.y+65});step(r,1);p.keys={};step(r,15);assert.equal(q.hp,100);});
test('zone shrinks to zero and damages outside, last survivor wins',()=>{assert.ok(B.zoneAt(110).r<B.zoneAt(0).r);assert.equal(B.zoneAt(350).r,0);const r=room();r.time=250;r.players[1].x=1200;r.players[1].y=1200;r.players[0].hp=.01;step(r,1);assert.equal(r.state,'finished');assert.equal(r.winner,1);});
test('disconnect freezes round and resumes original phase',()=>{const r=room();B.start(r);r.players[1].stream=false;step(r,1);assert.equal(r.state,'disconnected');assert.equal(r.selectTime,0);r.players[1].stream=true;act(r,0,'/pause');assert.equal(r.state,'selecting');});
test('invalid drop and stale match actions do not mutate state',()=>{const r=room();B.start(r);act(r,0,'/drop',{x:NaN,y:Infinity});assert.equal(r.players[0].selected,false);B.action(r,r.players[0],'/drop',{x:20,y:20,match:r.match-1});assert.equal(r.players[0].selected,false);});
test('network enforces two slots, host-only start, and sends guest-filtered state',()=>{const context={crypto:require('node:crypto').webcrypto,Battle:B,Date,document:{hidden:false},setInterval,clearInterval,clearTimeout};vm.createContext(context);vm.runInContext(fs.readFileSync('network.js','utf8')+';globalThis.Game=OnlineGame',context);const host=new context.Game(()=>{},()=>{});host.host=true;host.ready=true;host.room={players:[{slot:0,token:host.id,stream:true}]};B.reset(host.room);const messages=[];host.send=m=>messages.push(m);host.receive({kind:'join',id:'guest'});host.receive({kind:'join',id:'third'});assert.equal(host.room.players.length,2);assert.equal(messages.at(-1).ok,false);host.receive({kind:'action',id:'guest',path:'/start',data:{},actionId:1});assert.equal(host.room.state,'waiting');host.apply('/start',{},host.room.players[0]);assert.equal(host.room.state,'selecting');host.tick();host.tick();const message=messages.find(m=>m.kind==='state');assert.equal(message.to,'guest');assert.equal(message.state.players[0].x,undefined);});
test('browser scripts parse',()=>{for(const f of ['battle.js','network.js','game.js'])new vm.Script(fs.readFileSync(f,'utf8'));});
test('fully closed zone damages even its exact center and can draw',()=>{const r=room();r.time=350;r.players.forEach(p=>{p.x=1200;p.y=1200;p.hp=.01;});step(r,1);assert.equal(r.state,'finished');assert.equal(r.winner,null);});
test('render buffer creates intermediate positions and immediately conceals hidden enemies',()=>{const Motion=require('./motion'),buffer=new Motion(50),r=room();r.players.forEach(p=>p.y=1175);r.players[0].x=100;buffer.push(B.snapshot(r,1),0);r.players[0].x=120;buffer.push(B.snapshot(r,1),100);assert.equal(buffer.sample(100).players[0].x,110);assert.equal(buffer.sample(125).players[0].x,115);const h=B.buildings[0];r.players[0].x=h.x+50;r.players[0].y=h.y+50;buffer.push(B.snapshot(r,1),150);assert.equal(buffer.sample(155).players[0].visible,false);assert.equal(buffer.sample(155).players[0].x,undefined);});
test('render buffer resets on a new match, preventing stale location interpolation',()=>{const Motion=require('./motion'),buffer=new Motion(50),r=room();buffer.push(B.snapshot(r,0),0);B.reset(r);buffer.push(B.snapshot(r,0),20);assert.equal(buffer.frames.length,1);assert.equal(buffer.sample(25).state,'waiting');});
