const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm');
const {reset,update,choose,snapshot,spawn}=require('./engine');
function room(){const r={players:[{slot:0,stream:true},{slot:1,stream:true}]};reset(r);r.state='playing';r.spawn=999;return r;}
test('independent movement and pause',()=>{const r=room();r.players[0].keys={right:true};r.players[0].inputAt=Date.now();update(r,.1);assert.equal(r.players[0].x,22);assert.equal(r.players[1].x,90);r.state='paused';update(r,1);assert.equal(r.time,.1);});
test('revive and defeat',()=>{const r=room();r.players[1].x=0;r.players[1].hp=0;for(let i=0;i<91;i++)update(r,1/30);assert.equal(r.players[1].hp,50);r.players.forEach(p=>p.hp=0);update(r,.1);assert.equal(r.state,'lost');});
test('victory and disconnect',()=>{const r=room();r.time=599.99;update(r,.1);assert.equal(r.state,'won');reset(r);r.state='playing';r.players[1].stream=false;update(r,.1);assert.equal(r.state,'disconnected');});
test('team upgrades apply once',()=>{const r=room();r.state='upgrade';r.choices=[['power']];choose(r,'power');choose(r,'power');assert.deepEqual(r.players.map(p=>p.damage),[30,30]);assert.equal(snapshot(r).players[0].online,true);});
test('shots kill and XP collects',()=>{const r=room();r.enemies=[{id:1,x:70,y:0,hp:20,size:12,speed:0,damage:0}];for(let i=0;i<30;i++)update(r,1/30);assert.equal(r.kills,1);assert.ok(r.xp>0);});
test('host limits admission and start authority',()=>{const context={crypto:require('node:crypto').webcrypto,reset,spawn,update,choose,snapshot,Date,document:{hidden:false},setInterval,clearInterval,clearTimeout};vm.createContext(context);vm.runInContext(fs.readFileSync('network.js','utf8')+';globalThis.Game=OnlineGame',context);const host=new context.Game(()=>{},()=>{});host.host=true;host.room={players:[{slot:0,token:host.id,stream:true}]};reset(host.room);const messages=[];host.send=m=>messages.push(m);host.receive({kind:'join',id:'guest'});host.receive({kind:'join',id:'third'});assert.equal(host.room.players.length,2);assert.equal(messages.at(-1).ok,false);host.receive({kind:'action',id:'guest',path:'/start',data:{}});assert.equal(host.room.state,'waiting');host.apply('/start',{},host.room.players[0]);assert.equal(host.room.state,'playing');});
test('browser script syntax',()=>{const html=fs.readFileSync('index.html','utf8');for(const [,code]of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(code);});
